name: Test CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v3
    - uses: mlugg/setup-zig@v2
      with:
        version: 0.15.1
    - name: Run Tests
      run: |
        zig build test

