
name: Zig CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v3
    - uses: mlugg/setup-zig@v2
      with:
        version: 0.15.1
    - name: Install Zig
      run: |
        sudo apt-get update
        sudo apt-get install libglu1-mesa-dev mesa-common-dev xorg-dev libasound-dev
    - name: Run Tests
      run: |
        zig build test
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@main
      - uses: mlugg/setup-zig@v2
        with:
          version: 0.15.1
      - name: prepare-linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install libglu1-mesa-dev mesa-common-dev xorg-dev libasound-dev
      - name: build Native
        run: |
          zig build examples --summary all
      - name: build Native with gl
        run: |
          zig build examples --summary all -Dgl
      - name: build Wasm
        run: |
          zig build examples --summary all -Dtarget=wasm32-emscripten
      - name: build Wasm with wgpu
        run: |
          zig build examples --summary all -Dtarget=wasm32-emscripten -Dwgpu
